name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: Install GCC
      run: sudo apt-get install g++

    - uses: actions/checkout@v2
    - name: make
      run: make
